### PR TITLE
Gnome 46 support

### LINKED ISSUE #133: Gnome 46
```
gnome-shell[1788]: Extension quick-settings-tweaks@qwreey: Error: No signal 'actor-added' on object 'StWidget'

Stack trace:
enable@file:///home/user/.local/share/gnome-shell/extensions/quick-settings-tweaks@qwreey/extension.js:70:55
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:266:38
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:478:32
async*reloadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:526:20
async*_onVersionValidationChanged@resource:///org/gnome/shell/ui/extensionSystem.js:672:24
async*_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:740:18
@resource:///org/gnome/shell/ui/init.js:21:20
```

### PR DESCRIPTION
**Pull request by Anuskuss**
Closes #133.

### CODE REVIEW

**Comment by Striffly** [comment]
When I build I got this error :
```bash
Child process exited with code 1
Failed to pack extension
```
It's related with `gnome-extensions pack`

Does this happens also to you ?

**Comment by Anuskuss** [comment]
I didn't build it, I made those changes locally from the files I got from [GNOME Shell Extensions](https://extensions.gnome.org/extension/5446/quick-settings-tweaker).

**Comment by qwreey** [comment]
This pull request removes g45 supports (even can), and another pull request fixed this issue. Sorry for closing your pull request, but the issue was resolved for now

**Comment by Anuskuss** [comment]
> This pull request removes g45 supports (even can), and another pull request fixed this issue.

Yes, it fixed the issue but it also removed GNOME 45 support, it just didn't tell you. If you want GNOME 45 support you're going to need to do something like
```js
import * as Config from 'resource:///org/gnome/shell/misc/config.js';
const [major, minor] = Config.PACKAGE_VERSION.split('.').map(s => Number(s));

this.menuItemAddedTracker = QuickSettingsGrid.connect(major < 46 ? "actor-added" : "child-added",()=>{
```

**Pull request closed without merging**
